version: 2

jobs:
  check-itunes-status:
    docker: 
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dirty-cache-v1
      - run: sudo gem install fastlane 
      - run: npm install @slack/client@3.16.0 --save
      - run: npm install dirty --save
      - run: npm install moment --save
      - run: node poll-itc.js
      - save_cache:
          key: dirty-cache-v1
          paths:
            - "kvstore.db"

workflows:
  version: 2
  check-itunes-status:
    jobs:
      - check-itunes-status